(module True_survivor (
    (let make_lyrics () {
        (let lyrics (vector))

        (Std.Vector.push lyrics "Dominoes Falling")
        (Std.Vector.push lyrics "Riot in the streets")
        (Std.Vector.push lyrics "Baby this time")
        (Std.Vector.push lyrics "there's no retreat")
        (Std.Vector.push lyrics "there's no surrender")
        (Std.Vector.push lyrics "A devil is rising")
        (Std.Vector.push lyrics "a shadow from the past")
        (Std.Vector.push lyrics "feeding the flames with fire")
        (Std.Vector.push lyrics "on the edge of fury.")
        (Std.Vector.push lyrics "Out of time.")
        (Std.Vector.push lyrics "Runing in and out of time.")
        (Std.Vector.push lyrics "Hear the ticking of the")
        (Std.Vector.push lyrics "countdown clocks tonight.")
        (Std.Vector.push lyrics "Girl we need some")
        (Std.Vector.push lyrics "Girl we need some")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "If we re gonna make it like a true survivor")
        (Std.Vector.push lyrics "We need some")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "If we wanna take our love away from here")
        (Std.Vector.push lyrics "We need a")
        (Std.Vector.push lyrics "living passion")
        (Std.Vector.push lyrics "to belive in")
        (Std.Vector.push lyrics "Burning hearts")
        (Std.Vector.push lyrics "and a brand new feeling.")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "If we re gonna make it like a true survivor.")
        (Std.Vector.push lyrics "Wo oooh.")
        (Std.Vector.push lyrics "Crawling from the ashes")
        (Std.Vector.push lyrics "The phoenix rise again")
        (Std.Vector.push lyrics "Fighting for life")
        (Std.Vector.push lyrics "For good")
        (Std.Vector.push lyrics "For all that we belive in")
        (Std.Vector.push lyrics "Girl we need some")
        (Std.Vector.push lyrics "Girl we need some")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "If we re gonna make it like a true survivor")
        (Std.Vector.push lyrics "We need some")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "If we wanna take our love away from here")
        (Std.Vector.push lyrics "We need a")
        (Std.Vector.push lyrics "Living passion")
        (Std.Vector.push lyrics "To belive in")
        (Std.Vector.push lyrics "Burning hearts")
        (Std.Vector.push lyrics "and a brand new feeling")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "If we re gonna make it like a true survivor")
        (Std.Vector.push lyrics "The hero stands alone")
        (Std.Vector.push lyrics "When all is said and done")
        (Std.Vector.push lyrics "the enemies have fallen")
        (Std.Vector.push lyrics "one by one")
        (Std.Vector.push lyrics "Out of time")
        (Std.Vector.push lyrics "Running in and out of time")
        (Std.Vector.push lyrics "Hear the ticking of the")
        (Std.Vector.push lyrics "countdown clocks tonight")
        (Std.Vector.push lyrics "Girl we need")
        (Std.Vector.push lyrics "Girl we need some")
        (Std.Vector.push lyrics "Actiooooooaaaaaaaaeeeeeooooouh.")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "Woooaw")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "If we re gonna make it like a true survivor")
        (Std.Vector.push lyrics "We need some")
        (Std.Vector.push lyrics "Action!")
        (Std.Vector.push lyrics "Action")
        (Std.Vector.push lyrics "If we wanna take our love away from here")
        (Std.Vector.push lyrics "We need a")
        (Std.Vector.push lyrics "living passion")
        (Std.Vector.push lyrics "to belive in")
        (Std.Vector.push lyrics "burning hearts")
        (Std.Vector.push lyrics "and a brand new felling")
        (Std.Vector.push lyrics "If we re gonna make it like a true survivor")
        (Std.Vector.push lyrics "True survivor")
        (Std.Vector.push lyrics "Wooaaaohoaaa")
        (Std.Vector.push lyrics "True survivor")
        (Std.Vector.push lyrics "Wooaaaohoaaa")
        (Std.Vector.push lyrics "True survivor.")

        lyrics
    })
))
(import True_survivor)

(let for_each (v fn) {
    (let for_each_impl (v fn i limit) {
        (if (< i limit) {
            (fn (Std.Vector.at v i))
            (tailcall for_each_impl v fn (+ i 1) limit)
            0
        } 0)
    })
    (tailcall for_each_impl v fn 0 (Std.Vector.size v))
    0
})

(let main () {
    (let lyrics (True_survivor.make_lyrics))

    (let printer (x) {
        (print x)
    })
    (for_each lyrics printer)

    0
})
